# This provides the default setup, but it also requires some packages that are
# not available in the dev container. It can be commented out, but some
# functionality of HA won't be initialized yet.
# https://www.home-assistant.io/integrations/default_config/
# default_config:

# Alternatives instead of using default_config
config:
energy:
mobile_app:

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.zaptec: debug
    azure.servicebus: warning
