#!/usr/bin/env bash

set -e

if [ "$1" == "--skip-api" ]; then
    export SKIP_ZAPTEC_API_TEST="true"
fi
# run tests with -s to display printouts and --log-cli-level to get logger output
pytest --cov=./custom_components/zaptec --cov-branch --log-cli-level=INFO -s

# generate coverage report in html and xml
coverage html
coverage xml