name: Validate

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions: {}

jobs:
  hassfest: # https://developers.home-assistant.io/blog/2020/04/16/hassfest
    name: Hassfest validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Run hassfest validation
        uses: home-assistant/actions/hassfest@master

  hacs: # https://github.com/hacs/action
    name: HACS validation
    runs-on: ubuntu-latest
    steps:
      - name: Run HACS validation
        uses: hacs/action@main
        with:
          category: integration

  lint-ruff:
    name: Ruff validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Run ruff format
        uses: astral-sh/ruff-action@0ce1b0bf8b818ef400413f810f8a11cdbda0034b # v4.0.0
        with:
          args: format --diff
          src: "."

      - name: Run ruff check
        uses: astral-sh/ruff-action@0ce1b0bf8b818ef400413f810f8a11cdbda0034b # v4.0.0
        with:
          args: check --exit-zero # succeed despite errors until https://github.com/custom-components/zaptec/issues/258 is done
          src: "."

      - name: Run strict ruff check (except api.py)
        uses: astral-sh/ruff-action@v3
        with:
          args: check --exclude custom_components/zaptec/zaptec/api.py
          src: "."

  manifest-requirements:
    name: Manifest requirements validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout zaptec repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Check manifest requirements against latest HA dev branch
        run: |
          cd ${{ github.workspace }}
          python3 scripts/check_requirements.py --current-ha-dev

      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: changes
        with:
          filters: |
            requirement_files:
              - 'custom_components/zaptec/manifest.json'
              - 'hacs.json'

      - name: Check minimum HA version if manifest.json or hacs.json changed
        if: steps.changes.outputs.requirement_files == 'true'
        run: |
          cd ${{ github.workspace }}
          python3 scripts/check_requirements.py --minimum-ha-version

  tests:
    name: Unit testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13", "3.14"] # If 3.13-tests start failing, we need to consider setting HA2026.3 as the minimum version.
    steps:
      - name: Checkout the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Revert HA requirement to last version supporting Python ${{ matrix.python-version }}
        if: matrix.python-version == '3.13'
        run: |
          sed -i 's/^homeassistant==.*/homeassistant==2026.2.3/' requirements.txt

      - name: Install requirements
        run: |
          pip install \
              -r requirements.txt \
              -r requirements_test.txt

      - name: Tests suite
        run: |
          pytest --cov=./custom_components/zaptec --cov-branch

