name: Validate

on:
  workflow_dispatch:
  push:
  pull_request:

permissions: {}

env:
  DEFAULT_PYTHON: 3.13

jobs:
  hassfest: # https://developers.home-assistant.io/blog/2020/04/16/hassfest
    name: Hassfest validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Run hassfest validation
        uses: home-assistant/actions/hassfest@master

  hacs: # https://github.com/hacs/action
    name: HACS validation
    runs-on: ubuntu-latest
    steps:
      - name: Run HACS validation
        uses: hacs/action@main
        with:
          category: integration

  lint-ruff:
    name: Ruff validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Run ruff format
        uses: astral-sh/ruff-action@v3
        with:
          args: format --diff
          src: "."

      - name: Run ruff check
        uses: astral-sh/ruff-action@v3
        with:
          args: check --exit-zero # succeed despite errors until https://github.com/custom-components/zaptec/issues/258 is done
          src: "."

  tests:
    name: Unit testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Python {{ "${{ env.DEFAULT_PYTHON }}" }}
        uses: "actions/setup-python@v5"
        with:
          python-version: {{ "${{ env.DEFAULT_PYTHON }}" }}

      - name: Install requirements
        run: |
          pip install \
              -r requirements.txt \
              -r requirements_test.txt

      - name: Tests suite
        run: |
          pytest
